<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559436780',
    'hitsid' => 'c-1-1',
    'views' => '11',
    'yesterdayviews' => '0',
    'dayviews' => '11',
    'weekviews' => '11',
    'monthviews' => '11',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433900',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433925',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433925',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433925',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433925',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433954',
    'hitsid' => 'c-1-19',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433954',
    'hitsid' => 'c-1-22',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433954',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  28 => 
  array (
    'id' => '28',
    'catid' => '9',
    'typeid' => '0',
    'title' => 'Popcorn Revulotion',
    'style' => '',
    'thumb' => '',
    'keywords' => 'Popcorn Revulotion',
    'description' => 'Popcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn RevulotionPopcorn Revulot   ',
    'posids' => '0',
    'url' => 'http://localhost/iphone/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'xhadmin',
    'inputtime' => '1559433447',
    'updatetime' => '1559433954',
    'hitsid' => 'c-1-28',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>